### ISSUE TITLE
Feature request: Official way of creating external plugins

### ISSUE THREAD

**Issue by davidolrik** [DandyDev/slack-machine#285]
I have created a few plugins I would like to distribute seperately on PyPI.

For now I have created them in a new top-level namespace like `slack_machine_plugin_<name>`, but this seems inelegant, and the doc-strings are not picked up for the help command.

Thoughts?

**Comment by DandyDev** [comment]
I'm wondering why the doc-strings aren't picked up by the help command. I always assumed that external plugins distributed via PyPI would work out of the box.
I will do some research this week to see how to get it to work and get back to you on this issue.

**Comment by davidolrik** [comment]
Excellent - I tried to create a namespaced package in `machine.plugins.external.<name>`, but failed as I couldn't get it to load the module from within that package.

**Comment by DandyDev** [comment]
Update: Yesterday, I pushed a major update for Slack Machine. Sadly, it's not fully backwards compatible. I had to update quite some of the inner workings of Slack Machine because the underlying slack client library I'm using also had some big breaking changes.

I also took some time to create an example plugin to show people how it's done. You can find the repo here: https://github.com/DandyDev/sm-example-plugin. I didn't publish the package to PyPI (although I could, I guess), but you can easily install it by providing `pip` with the Github URL. It's all in the README of the example plugin.

Help texts are also confirmed to work.

Let me know if that clears things up for you, and feel free to ask any questions!

**Comment by davidolrik** [comment]
I see you also use a different top level name space for your plugin and plugins for other python projects also live out side the name space of the main project - guess it's just the Python way of doing things.
