### ISSUE TITLE
msg.say() in DM throws error

### ISSUE THREAD

**Issue by davidolrik** [DandyDev/slack-machine#323]
After upgrading to 0.19.2 I had to change `say_webapi()` to `say()` which unfortunately seems to have broken replies in DMs.

```
  File "/Users/me/bot/plugins/noru.py", line 36, in rebuild
    msg.say('Nice message')
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/bot-UaO2qz8g-py3.8/lib/python3.8/site-packages/machine/plugins/base.py", line 340, in say
    self.channel.id,
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/bot-UaO2qz8g-py3.8/lib/python3.8/site-packages/machine/plugins/base.py", line 275, in channel
    return self._client.channels[self._msg_event['channel']]
KeyError: 'DJDUJ1000'
```

**Comment by DandyDev** [comment]
I've had a colleague of mine report a similar error. I don't know exactly what is happening here yet, but I can give you some context.
As part of the upgrade of the underlying `slackclient` library to > 2.0, I lost the ability to lookup channels and users. The newer versions of `slackclient` don't keep records of users and channels anymore, because the RTM method to fetch all users and channels upon connecting, was deprecated. Obviously it's sorely needed functionality to be able to lookup all users and channels, so I rebuilt this functionality into Slack Machine using officially supported webapi methods to fetch all users and channels upon SM startup.
Apparently, building up the users and channels dictionaries doesn't result in a complete dict of channels. Hence the missing key.

I have to do some more digging to find out what is going wrong exactly.

**Comment by dorel14** [comment]
Hello
Perhaps it's linked with #308 in which i've seen error when respond_to in private channels

**Comment by unl1k3ly** [comment]
any update on this ?

**Comment by DandyDev** [comment]
You can upgrade to [v0.20](https://pypi.org/project/slack-machine/0.20.0/) to get the fixes
