### ISSUE TITLE
Easy way to process "listen_to" and "respond_to" without duplicating the regex?

### ISSUE THREAD

**Issue by eddyg** [DandyDev/slack-machine#435]
I was just looking at the [dispatch code here](https://github.com/DandyDev/slack-machine/blob/master/machine/dispatch.py#L39-L49) where `listen_to` and `respond_to` are handled.

I'd like to have a bot be able to respond to a regex "trigger" _without_ being addressed in a public channel (`listen_to`), _and_ allow the same trigger in a private message to the bot to return the same info via a private reply (`respond_to`).

It seems like the only way to do that right now is to add **both** decorators, duplicating the (in this case, somewhat complex) regex, where they could get easily out of sync. In addition, there is all the internal duplication in `_register_plugin_actions()`, which then _also_ doubles up `robot help`, etc..

I'm thinking a `@listen_or_respond_to` decorator could set up a `respond_to` action with a new flag that indicates whether or not the `respond_to_msg` check should be ignored. Does that seem reasonable? Would a PR with that functionality be accepted?

**Comment by DandyDev** [comment]
Hey @eddyg, I'm only seeing this issue and your PR now. Your contribution is much appreciated. I do wonder however, if what you're describing (bot responding to "naked" messages without mention and _also_ responding to the same regex in a DM convo) shouldn't be the default behaviour of `listen_to`. Then we wouldn't need an extra decorator. Then the only difference between `listen_to` and `respond_to` would be in non-DM messages because you'd need to mention the bot in case of `respond_to`.

Your thoughts?

**Comment by eddyg** [comment]
That sounds good to me (and how I expected plugins to work during my testing). I didn't know if a substantial change in behavior like that would be acceptable or not, so I went the "safe" route with my PR. 😉
