### ISSUE TITLE
Does slack-machine support or plans to support plugins that can be built for multiple teams?

### ISSUE THREAD

**Issue by SachinBhat** [DandyDev/slack-machine#7]
I was looking at building a bot that can be installed across multiple independent teams. The few changes that might be required then is how a plugin will identify and connect to different teams as well as support a webserver microservice. I dont think slack-machine is supporting the above at the moment but wanted to confirm if it is in the works?

**Comment by DandyDev** [comment]
Slack Machine currently doesn't work with multiple teams. You'd have to run
a separate instance of Slack Machine per team.
I do want to implement this, but don't count on it very soon. Slack Machine
is currently still a one-man show, so time is sparse. Also, Slack Machine
is quite new, so I first want to gather feedback on how the current
iteration works and implement fixes based on that.

A webserver is higher up the todo list, because it's also needed to support
interactive buttons and such.

Of course, the biggest cliché with regards to open source, is true here as
well: pull requests are welcome! If you feel like tackling any of the
aforementioned changes, it might be good to share a rough outline on the
solution with me first :)

**Comment by DandyDev** [comment]
I'm assuming this answers the question, so I'm closing this ticket. If you have any further questions on the subject, feel free to open the ticket again!
